PATH = {
	"g(x)": { 
		"Truth table": "g(x)/truth_table.txt",
		"Walsh spectrum table": "g(x)/walsh_spectrum_table.txt",
		"ANF table": "g(x)/anf_table.txt",
		"MDP": "g(x)/mdp.txt",
		"Algebraic degree": "g(x)/algebraic_degree.txt",
		"Disbalance": "g(x)/disbalance.txt",
		"RDE": "g(x)/rde.txt",
		"Nonlinearity": "g(x)/nonlinearity.txt",
		"k-balance": "g(x)/k_balance.txt",
		"Relative deviation of RDE": "g(x)/relative_deviation_rde.txt",
		"Correlation immunity": "g(x)/correlation_immunity.txt"},
	"f(x)": {
		"Truth table": "f(x)/truth_table.txt",
		"Walsh spectrum table": "f(x)/walsh_spectrum_table.txt",
		"ANF table": "f(x)/anf_table.txt",
		"MDP": "f(x)/mdp.txt",
		"Algebraic degree": "f(x)/algebraic_degree.txt",
		"Disbalance": "f(x)/disbalance.txt",
		"RDE": "g(x)/rde.txt",
		"Nonlinearity": "f(x)/nonlinearity.txt",
		"k-balance": "f(x)/k_balance.txt",
		"Relative deviation of RDE": "f(x)/relative_deviation_rde.txt",
		"Correlation immunity": "f(x)/correlation_immunity.txt"},
	}
